# Generated by Django 5.1.1 on 2025-06-13 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodacceptor',
            name='donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donateapp.fooddonare'),
        ),
        migrations.AddField(
            model_name='foodacceptor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
