# Generated by Django 5.1.1 on 2025-06-13 06:25

import datetime
import donateapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0002_foodacceptor_donation_foodacceptor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonare',
            name='expiry_time',
            field=models.DateTimeField(default=donateapp.models.default_expiry),
        ),
        migrations.AddField(
            model_name='fooddonare',
            name='prepared_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 6, 25, 33, 47270, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
