# Generated by Django 5.1.1 on 2025-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0003_fooddonare_expiry_time_fooddonare_prepared_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonare',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonare',
            name='prepared_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
